apiVersion: v1
kind: Service
metadata:
  name: airflow-webserver
spec:
  type: NodePort
  ports:
  - port: 8080
    targetPort: 8080
    nodePort: 30080  # Optional: specify a nodePort; otherwise, one is automatically assigned
  selector:
    component: airflow-webserver
